version: "3.8"

services:
  api:
    build:
      context: ./app # Points to the app directory
      dockerfile: Dockerfile.prod # Use the production Dockerfile
    image: eventorize-api:latest
    restart: always
    command: uvicorn main:app --workers 1 --host 0.0.0.0 --port 8005
    volumes:
      - ./logs/:/opt/projects/app/logs
    ports:
      - "8005:8005"
    env_file:
      - ./.env/prod.env
      - .env/db.env
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import requests; requests.get('http://localhost:8005/v1/health/ping').raise_for_status()",
        ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - db

  db:
    image: mongo:8.0.4
    restart: always
    volumes:
      - ./database:/data/db
    command: --quiet
    ports:
      - "27017:27017"
    env_file:
      - ./.env/db.env
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin --username $$MONGO_INITDB_ROOT_USERNAME --password $$MONGO_INITDB_ROOT_PASSWORD --quiet | grep 1
      interval: 60s
      timeout: 60s
      retries: 6
