name: Deploy to VPS

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: Creating .env file
        run: |
          mkdir -p .env
          echo "ENVIRONMENT=$ENVIRONMENT" > .env/dev.env  # Changed from test.env to dev.env
          echo "APP_DATABASE_NAME=$APP_DATABASE_NAME" >> .env/dev.env
          echo "DATABASE_URL=$DATABASE_URL" >> .env/dev.env
          echo "SECRET_KEY=$SECRET_KEY" >> .env/dev.env
          echo "ALGORITHM=$ALGORITHM" >> .env/dev.env
          echo "DEFAULT_ADMIN_EMAIL=$DEFAULT_ADMIN_EMAIL" >> .env/dev.env
          echo "DEFAULT_ADMIN_PASSWORD=$DEFAULT_ADMIN_PASSWORD" >> .env/dev.env
        shell: bash
        env:
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          APP_DATABASE_NAME: ${{ secrets.APP_DATABASE_NAME }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ALGORITHM: ${{ secrets.ALGORITHM }}
          DEFAULT_ADMIN_EMAIL: ${{ secrets.DEFAULT_ADMIN_EMAIL }}
          DEFAULT_ADMIN_PASSWORD: ${{ secrets.DEFAULT_ADMIN_PASSWORD }}

      - name: "Run tests"
        run: chmod +x bin/linux/test.sh && ./bin/linux/test.sh

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        working-directory: app
        run: docker build -t eventorize-api:latest -f Dockerfile.prod .

      - name: Save Docker image
        run: docker save eventorize-api:latest > eventorize-api.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: eventorize-api.tar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa,ecdsa,ed25519 "$VPS_HOST" >> ~/.ssh/known_hosts

      - name: Copy deployment files
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
        run: |
          # Copy both Docker image and compose file
          scp eventorize-api.tar $VPS_USERNAME@$VPS_HOST:~/
          scp docker-compose-product.yml $VPS_USERNAME@$VPS_HOST:/root/eventorize-api-huflit/

      - name: Deploy to VPS
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
        run: |
          # Create environment files locally
          echo "${{ secrets.PROD_ENV }}" > prod.env
          echo "${{ secrets.DB_ENV }}" > db.env

          # Create necessary directories on VPS
          ssh $VPS_USERNAME@$VPS_HOST "mkdir -p /root/eventorize-api-huflit/.env"

          # Copy files to VPS
          scp prod.env $VPS_USERNAME@$VPS_HOST:/root/eventorize-api-huflit/.env/prod.env
          scp db.env $VPS_USERNAME@$VPS_HOST:/root/eventorize-api-huflit/.env/db.env
          scp eventorize-api.tar $VPS_USERNAME@$VPS_HOST:~/
          scp docker-compose-product.yml $VPS_USERNAME@$VPS_HOST:/root/eventorize-api-huflit/

          # Deploy on VPS
          ssh $VPS_USERNAME@$VPS_HOST << 'EOF'
            cd /root/eventorize-api-huflit
            
            # Verify env files exist
            if [ ! -f ".env/prod.env" ] || [ ! -f ".env/db.env" ]; then
              echo "ERROR: Environment files not found!"
              ls -la .env/
              exit 1
            fi

            # Load Docker image and continue deployment
            docker load < ~/eventorize-api.tar

            # Stop and remove old container
            if docker-compose -f docker-compose-product.yml ps | grep api; then
              docker-compose -f docker-compose-product.yml stop api
              docker-compose -f docker-compose-product.yml rm -f api
            fi

            # Start updated API container
            docker-compose -f docker-compose-product.yml up -d api

            # Clean up
            docker image prune -f
            rm ~/eventorize-api.tar

            # Verify deployment
            if docker ps | grep eventorize-api; then
              echo "Deployment successful!"
            else
              echo "Deployment failed!"
              docker-compose -f docker-compose-product.yml logs api
              exit 1
            fi
          EOF

      - name: Verify Deployment
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
        run: |
          echo "Checking deployment status..."
          ssh $VPS_USERNAME@$VPS_HOST "docker ps | grep eventorize-api" || {
            echo "Deployment verification failed"
            exit 1
          }
          echo "Deployment verified successfully"
